---
apiVersion: v1
kind: Namespace
metadata:
  name: nagp-amcart-namespace

---
kind: Service
apiVersion: v1
metadata:
  name: apigw-np-service
  namespace: nagp-amcart-namespace
spec:
  type: NodePort
  selector:
    app: apigw-service
  ports:
  - port: 8082
    targetPort: 8082

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigw-config
  namespace: nagp-amcart-namespace
data:
  keycloak-server-url: 'http://35.225.180.167'
  search-service-url: 'http://search-np-service.nagp-amcart-namespace.svc.cluster.local:8081'

---
apiVersion: v1
kind: Secret
metadata:
  name: apigw-secret
  namespace: nagp-amcart-namespace
type: Opaque
data:
  clientSecret: ZDJsc2EwVEdrc0Vhakx4U0Vocmw3Z214T3FobFRMeEQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigw-deployment
  namespace: nagp-amcart-namespace
spec:
  selector:
      matchLabels:
        app: apigw-service
  replicas: 1
  template:
    metadata:
      labels:
        app: apigw-service
    spec:
      containers:
       - name: apigw-service
         image: us-central1-docker.pkg.dev/nagp-amcart-rakesh/nagp-amcart-repo/apigw-service:v1
         imagePullPolicy: Always
         envFrom:
            - configMapRef:
                name: apigw-config
            - secretRef:
                name: apigw-secret
         ports:
         - containerPort: 8082
         livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8082
              initialDelaySeconds: 30
              periodSeconds: 30
              failureThreshold: 3
         readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8082
              initialDelaySeconds: 15
              periodSeconds: 30
              failureThreshold: 3